In [17]:
import numpy as np

There stored some usefull exercises and usage cases of numpy.


Create a bolean array


In [18]:
np.full((3,3),True,dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Extract items that satisfy given condition.

In [20]:
arr = np.arange(10)
arr[arr%2 == 1]

array([1, 3, 5, 7, 9])

Replace item that satisfy a condition with another value

In [21]:
arr[arr%2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Replace items that satisfy a condition without affecting the original array

In [22]:
arr = np.arange(10)
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Reshape array

In [23]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

 How to stack two arrays vertically?

In [24]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1, 10).reshape(2,5)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

repeat vs tile

In [26]:
np.repeat(a,3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7,
       7, 7, 8, 8, 8, 9, 9, 9])

In [27]:
np.tile(a,3)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

How to get the common items between two python numpy arrays?

In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

How to remove from one array those items that exist in another?

In [29]:
np.setdiff1d(a, b)

array([1, 3, 5, 6])

Get the positions where elements of a and b match

In [30]:
np.where(a==b)

(array([1, 3, 5, 7]),)

How to make a python function that handles scalars to work on numpy arrays?

In [31]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
maxx(1,5)

5

In [32]:
pair_max = np.vectorize(maxx, otypes=[int])
pair_max(a, b)

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

How to swap two columns/rows in a 2d numpy array?

In [33]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [37]:
arr[[2,0,1], :]

array([[6, 7, 8],
       [0, 1, 2],
       [3, 4, 5]])

In [38]:
arr[::-1]#reverse

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

How set a precision?

In [40]:
rand_arr = np.random.random([2,2])
rand_arr

array([[0.29354913, 0.86050999],
       [0.68740133, 0.99729306]])

In [41]:
np.set_printoptions(precision=3)

In [55]:
rand_arr

array([[0.754, 0.664],
       [0.783, 0.636]])

How to import a dataset with numbers and texts keeping the text intact in python numpy?


In [56]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [72]:
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_2d[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])